const ES: Record<string, string> = {
  // América del Norte y Central
  "Mexico": "México",
  "United States": "Estados Unidos",
  "Canada": "Canadá",
  "Panama": "Panamá",
  "Costa Rica": "Costa Rica",
  "Honduras": "Honduras",
  "El Salvador": "El Salvador",
  "Guatemala": "Guatemala",
  "Cuba": "Cuba",
  "Jamaica": "Jamaica",
  "Trinidad and Tobago": "Trinidad y Tobago",

  // América del Sur
  "Argentina": "Argentina",
  "Brazil": "Brasil",
  "Colombia": "Colombia",
  "Uruguay": "Uruguay",
  "Paraguay": "Paraguay",
  "Peru": "Perú",
  "Chile": "Chile",
  "Ecuador": "Ecuador",
  "Bolivia": "Bolivia",
  "Venezuela": "Venezuela",

  // Europa
  "Spain": "España",
  "France": "Francia",
  "Germany": "Alemania",
  "England": "Inglaterra",
  "Netherlands": "Países Bajos",
  "Portugal": "Portugal",
  "Belgium": "Bélgica",
  "Italy": "Italia",
  "Croatia": "Croacia",
  "Denmark": "Dinamarca",
  "Switzerland": "Suiza",
  "Serbia": "Serbia",
  "Poland": "Polonia",
  "Hungary": "Hungría",
  "Czechia": "Rep. Checa",
  "Czech Republic": "Rep. Checa",
  "Slovakia": "Eslovaquia",
  "Slovenia": "Eslovenia",
  "Ukraine": "Ucrania",
  "Russia": "Rusia",
  "Turkey": "Turquía",
  "Wales": "Gales",
  "Scotland": "Escocia",
  "Greece": "Grecia",
  "Romania": "Rumania",
  "Austria": "Austria",
  "Sweden": "Suecia",
  "Norway": "Noruega",
  "Finland": "Finlandia",
  "Bosnia-Herzegovina": "Bosnia-Herz.",

  // Asia y Oceanía
  "Japan": "Japón",
  "South Korea": "Corea del Sur",
  "North Korea": "Corea del Norte",
  "Australia": "Australia",
  "New Zealand": "Nueva Zelanda",
  "Saudi Arabia": "Arabia Saudita",
  "Iran": "Irán",
  "Qatar": "Qatar",
  "Indonesia": "Indonesia",
  "Uzbekistan": "Uzbekistán",
  "Kyrgyzstan": "Kirguistán",

  // África
  "South Africa": "Sudáfrica",
  "Morocco": "Marruecos",
  "Egypt": "Egipto",
  "Nigeria": "Nigeria",
  "Senegal": "Senegal",
  "Ghana": "Ghana",
  "Cameroon": "Camerún",
  "Algeria": "Argelia",
  "Angola": "Angola",
  "Mali": "Malí",
  "Tunisia": "Túnez",
  "Ivory Coast": "Costa de Marfil",
  "Côte d'Ivoire": "Costa de Marfil",
  "DR Congo": "R. D. Congo",
  "Congo DR": "R. D. Congo",
  "Democratic Republic of Congo": "R. D. Congo",
  "Curaçao": "Curazao",
  "Haiti": "Haití",
  "Iraq": "Irak",
  "Jordan": "Jordania",
  "Cape Verde Islands": "Cabo Verde",
  "Cape Verde": "Cabo Verde",
  "Zambia": "Zambia",
  "Zimbabwe": "Zimbabue",
  "Tanzania": "Tanzania",
  "Mozambique": "Mozambique",
  "Guinea": "Guinea",
  "Equatorial Guinea": "Guinea Ecuatorial",
  "Guinea-Bissau": "Guinea-Bisáu",
  "Togo": "Togo",
  "Benin": "Benín",
  "Burkina Faso": "Burkina Faso",
  "Niger": "Níger",
  "Chad": "Chad",
  "Sudan": "Sudán",
  "Ethiopia": "Etiopía",
  "Kenya": "Kenia",
  "Uganda": "Uganda",
  "Rwanda": "Ruanda",
  "Liberia": "Liberia",
  "Sierra Leone": "Sierra Leona",
};

export function teamNameEs(name: string): string {
  return ES[name] ?? name;
}
